# Generated by Django 5.1.4 on 2025-11-18 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('good', 'Good / Working'), ('needs_repair', 'Needs Repair'), ('retired', 'Retired / Disposed'), ('lost', 'Lost')], default='good', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('useful_life_years', models.PositiveIntegerField(blank=True, help_text='Expected useful life in years for depreciation', null=True)),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value at the end of useful life', max_digits=12, null=True)),
                ('label', models.CharField(choices=[('donated', 'Donated'), ('church_provided', 'Church Provided')], default='church_provided', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('ministry_name', models.CharField(blank=True, help_text='Name of ministry that owns/uses this item', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['item_name', 'id'],
            },
        ),
    ]
