# Generated by Django 5.1.4 on 2025-11-18 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItem',
            new_name='InventoryTracking',
        ),
        migrations.AlterModelOptions(
            name='inventorytracking',
            options={'ordering': ['item_name', 'id'], 'verbose_name': 'Inventory Tracking', 'verbose_name_plural': 'Inventory Tracking'},
        ),
        migrations.AlterModelTable(
            name='inventorytracking',
            table='inventory_tracking',
        ),
    ]
