# Generated by Django 5.1.4 on 2025-11-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_inventoryitem_inventorytracking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytracking',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventorytracking',
            name='acquisition_cost',
        ),
        migrations.RemoveField(
            model_name='inventorytracking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventorytracking',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventorytracking',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventorytracking',
            name='label',
        ),
        migrations.RemoveField(
            model_name='inventorytracking',
            name='ministry_name',
        ),
        migrations.RemoveField(
            model_name='inventorytracking',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='inventorytracking',
            name='salvage_value',
        ),
        migrations.RemoveField(
            model_name='inventorytracking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='inventorytracking',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='inventorytracking',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytracking',
            name='status',
            field=models.CharField(default='good', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorytracking',
            name='useful_life_years',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterModelTable(
            name='inventorytracking',
            table=None,
        ),
    ]
