# Generated by Django 5.1.4 on 2025-11-18 14:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorytracking_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorytracking',
            old_name='cost',
            new_name='acquisition_cost',
        ),
        migrations.AddField(
            model_name='inventorytracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorytracking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytracking',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventorytracking',
            name='label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inventorytracking',
            name='ministry_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventorytracking',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventorytracking',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventorytracking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventorytracking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorytracking',
            name='status',
            field=models.CharField(default='good', help_text='e.g. good, needs_repair, retired, lost', max_length=50),
        ),
    ]
