# Generated by Django 5.1.4 on 2025-11-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_cost_inventorytracking_acquisition_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventorytracking',
            table='inventory_tracking',
        ),
    ]
