# Generated by Django 5.1.4 on 2025-11-02 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_alter_eventregistration_attended_and_more"),
        ("members", "0005_member_attendance_rate_member_consecutive_absences_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this attendance session"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event this sheet is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sheets",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_sheet",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("event", "date")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes about this attendance record"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="members.member",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="attendance.attendancesheet",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
                "ordering": ["-sheet__date", "member__last_name", "member__first_name"],
                "unique_together": {("sheet", "member")},
            },
        ),
    ]
