# Generated by Django 5.1.4 on 2025-11-02 15:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('events', '0001_initial'),
        ('members', '0004_member_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('event_title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_sheet',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.attendancesheet'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('sheet', 'event', 'member')},
        ),
    ]
