# Generated by Django 5.1.4 on 2025-11-13 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("events", "0003_remove_deprecated_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesheet",
            name="event",
            field=models.ForeignKey(
                help_text="Link to the event type (e.g., 'Sunday Service')",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_sheets",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="attendancesheet",
            name="notes",
            field=models.TextField(blank=True, help_text="Additional notes about this session"),
        ),
    ]
