# Generated by Django 5.1.4 on 2025-10-28 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='ministries.ministry')),
            ],
            options={
                'ordering': ['date', 'ministry'],
                'unique_together': {('ministry', 'role', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('reminded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='ministries.shift')),
            ],
            options={
                'ordering': ['shift', 'user'],
            },
        ),
        migrations.CreateModel(
            name='MinistryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('volunteer', 'Volunteer'), ('lead', 'Lead'), ('usher', 'Usher'), ('worship', 'Worship')], default='volunteer', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('max_consecutive_shifts', models.PositiveSmallIntegerField(default=2)),
                ('available_days', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_members', related_query_name='ministry_member', to='ministries.ministry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ministry', 'user'],
                'unique_together': {('user', 'ministry')},
            },
        ),
    ]
