# Generated by Django 5.1.4 on 2025-11-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministries", "0002_alter_ministry_leader_shift_assignment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ministrymember",
            options={"ordering": ["ministry__name", "user__username"]},
        ),
        migrations.AlterModelOptions(
            name="shift",
            options={"ordering": ["date", "start_time"]},
        ),
        migrations.RenameField(
            model_name="assignment",
            old_name="notified",
            new_name="attended",
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="reminded",
        ),
        migrations.AddField(
            model_name="assignment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ministry",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shift",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shift",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ministrymember",
            name="role",
            field=models.CharField(
                choices=[("volunteer", "Volunteer"), ("lead", "Lead")],
                default="volunteer",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="end_time",
            field=models.TimeField(default="17:00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shift",
            name="start_time",
            field=models.TimeField(default="17:00:00"),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="ministry",
            table=None,
        ),
        migrations.RemoveField(
            model_name="shift",
            name="role",
        ),
    ]
