# Generated by Django 5.1.4 on 2025-12-11 14:27
# MANUALLY FIXED: Reordered operations to avoid FieldDoesNotExist error

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_remove_user_fk"),
        ("ministries", "0003_remove_shift_role_field"),
    ]

    operations = [
        # === MINISTRYMEMBER: Fix unique_together before field changes ===
        # 1. First remove the OLD unique_together (uses 'user')
        migrations.AlterUniqueTogether(
            name="ministrymember",
            unique_together=set(),
        ),
        # 2. Add the new 'member' field
        migrations.AddField(
            model_name="ministrymember",
            name="member",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ministry_memberships",
                to="members.member",
            ),
            preserve_default=False,
        ),
        # 3. Remove the old 'user' field
        migrations.RemoveField(
            model_name="ministrymember",
            name="user",
        ),
        # 4. NOW add the NEW unique_together (uses 'member')
        migrations.AlterUniqueTogether(
            name="ministrymember",
            unique_together={("member", "ministry")},
        ),
        # 5. Update model options (ordering)
        migrations.AlterModelOptions(
            name="ministrymember",
            options={"ordering": ["ministry__name", "member__last_name", "member__first_name"]},
        ),
        # === ASSIGNMENT: Simple field swap ===
        # 6. Add 'member' field to Assignment
        migrations.AddField(
            model_name="assignment",
            name="member",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="members.member",
            ),
            preserve_default=False,
        ),
        # 7. Remove 'user' field from Assignment
        migrations.RemoveField(
            model_name="assignment",
            name="user",
        ),
    ]
