# Generated by Django 5.1.4 on 2025-12-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_member_attendance_rate_member_consecutive_absences_and_more"),
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visitor",
            options={"ordering": ["-date_added"]},
        ),
        migrations.AlterModelOptions(
            name="visitorattendance",
            options={"ordering": ["-service_date"]},
        ),
        migrations.AddField(
            model_name="visitor",
            name="converted_to_member",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to Member record if converted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_from_visitor",
                to="members.member",
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="follow_up_status",
            field=models.CharField(
                choices=[
                    ("visited_1x", "Visited 1x"),
                    ("visited_2x", "Visited 2x"),
                    ("regular", "Regular Visitor"),
                ],
                default="visited_1x",
                help_text="Follow-up tracking status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="notes",
            field=models.TextField(blank=True, help_text="Additional notes about the visitor"),
        ),
        migrations.AddField(
            model_name="visitor",
            name="status",
            field=models.CharField(
                choices=[("visitor", "Visitor"), ("member", "Member")],
                default="visitor",
                help_text="Mark as Visitor or Member",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
