# Generated by Django 5.1.4 on 2025-10-22 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('ministries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('service', 'Sunday Service'), ('bible_study', 'Bible Study'), ('prayer_meeting', 'Prayer Meeting'), ('fellowship', 'Fellowship'), ('outreach', 'Outreach'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('date', models.DateTimeField(help_text='Event start date and time')),
                ('end_date', models.DateTimeField(blank=True, help_text='Event end date and time', null=True)),
                ('location', models.CharField(max_length=200)),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees (leave blank for unlimited)', null=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this a recurring event?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry', models.ForeignKey(blank=True, help_text='Ministry organizing this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ministries.ministry')),
                ('organizer', models.ForeignKey(help_text='User organizing this event', on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False, help_text='Did the member attend?')),
                ('check_in_time', models.DateTimeField(blank=True, help_text='When member checked in', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about registration/attendance')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='members.member')),
            ],
            options={
                'db_table': 'event_registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'member')},
            },
        ),
    ]
