# Generated by Django 5.1.4 on 2025-11-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="attended",
            field=models.BooleanField(default=False, help_text="DEPRECATED: Use Attendance model"),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="check_in_time",
            field=models.DateTimeField(
                blank=True, help_text="DEPRECATED: Use Attendance model", null=True
            ),
        ),
    ]
