# Generated by Django 5.1.4 on 2025-11-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_eventregistration_attended_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="notes",
            field=models.TextField(blank=True, help_text="Notes about registration"),
        ),
    ]
