# Generated by Django 5.1.4 on 2026-01-25 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_deprecated_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="is_recurring",
        ),
        migrations.AddField(
            model_name="event",
            name="parent_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent event if this is a generated occurrence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrences",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_end_date",
            field=models.DateField(
                blank=True, help_text="Stop generating occurrences after this date", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_pattern",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Every 2 Weeks"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                help_text="How often this event repeats",
                max_length=20,
            ),
        ),
    ]
