# Generated by Django 5.1.4 on 2025-12-10 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.meeting_minutes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ministries", "0003_remove_shift_role_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingMinutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("meeting_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("finance", "Finance"),
                            ("worship", "Worship"),
                            ("youth", "Youth"),
                            ("outreach", "Outreach"),
                            ("administrative", "Administrative"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField(help_text="Meeting notes and decisions")),
                ("attendees", models.TextField(blank=True, help_text="List of attendees")),
                ("is_active", models.BooleanField(default=True, help_text="Soft delete flag")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_meeting_minutes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ministry this meeting belongs to (optional for general meetings)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_minutes",
                        to="ministries.ministry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Minutes",
                "verbose_name_plural": "Meeting Minutes",
                "db_table": "meeting_minutes",
                "ordering": ["-meeting_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingMinutesAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=apps.meeting_minutes.models.MeetingMinutesAttachment.upload_to_path,
                    ),
                ),
                ("file_name", models.CharField(help_text="Original filename", max_length=255)),
                ("file_size", models.PositiveIntegerField(help_text="File size in bytes")),
                ("file_type", models.CharField(help_text="File extension", max_length=50)),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True, help_text="Extracted text content for full-text search"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting_minutes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="meeting_minutes.meetingminutes",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meeting_minutes_attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingMinutesVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("content", models.TextField(help_text="Content snapshot at this version")),
                (
                    "change_summary",
                    models.CharField(
                        blank=True, help_text="Brief description of changes", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_minutes_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting_minutes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="meeting_minutes.meetingminutes",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_minutes_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddIndex(
            model_name="meetingminutes",
            index=models.Index(
                fields=["category", "meeting_date"], name="meeting_min_categor_e74190_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingminutes",
            index=models.Index(
                fields=["ministry", "meeting_date"], name="meeting_min_ministr_ee242c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingminutes",
            index=models.Index(
                fields=["is_active", "meeting_date"], name="meeting_min_is_acti_f6197c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meetingminutesversion",
            unique_together={("meeting_minutes", "version_number")},
        ),
    ]
