# Generated by Django 5.1.4 on 2026-01-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_role_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User profile picture (recommended: 200x200px)",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
