# Generated by Django 5.1.4 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_add_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("pastor", "Pastor"),
                    ("ministry_leader", "Ministry Leader"),
                    ("multimedia", "Multimedia"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
