# Generated by Django 5.1.4 on 2025-12-09 20:17

from django.db import migrations, models

import apps.tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattachment",
            name="content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="taskattachment",
            name="file",
            field=models.FileField(
                max_length=500, upload_to=apps.tasks.models.TaskAttachment.upload_to_path
            ),
        ),
        migrations.AlterField(
            model_name="taskattachment",
            name="file_name",
            field=models.CharField(help_text="Original filename", max_length=255),
        ),
    ]
