# Generated by Django 5.1.4 on 2025-12-01 12:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '0003_remove_shift_role_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All Members'), ('ministry', 'Specific Ministry')], default='all', help_text='Who should receive this announcement', max_length=20)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this announcement becomes visible')),
                ('expire_at', models.DateTimeField(blank=True, help_text='Optional: When this announcement expires', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sent', models.BooleanField(default=False, help_text='Has email notification been sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, help_text="Required if audience is 'ministry'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='ministries.ministry')),
            ],
            options={
                'ordering': ['-publish_at'],
                'indexes': [models.Index(fields=['-publish_at'], name='announcemen_publish_4ee3c6_idx'), models.Index(fields=['audience', 'ministry'], name='announcemen_audienc_72d51e_idx')],
            },
        ),
    ]
