# Generated by Django 5.1.4 on 2026-01-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo for this announcement",
                null=True,
                upload_to="announcements/%Y/%m/",
            ),
        ),
    ]
