# Generated by Django 5.1.4 on 2026-01-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0003_alter_announcement_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo for this announcement",
                null=True,
                upload_to="announcements/",
                verbose_name="Photo",
            ),
        ),
    ]
