# Generated by Django 5.1.4 on 2025-10-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
