# Generated by Django 5.1.4 on 2025-11-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_member_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="attendance_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Overall attendance percentage", max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="consecutive_absences",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of consecutive absences"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="last_attended",
            field=models.DateField(blank=True, help_text="Last attendance date", null=True),
        ),
    ]
