# Generated by Django 5.1.4 on 2025-12-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_member_attendance_rate_member_consecutive_absences_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="user",
        ),
        migrations.AlterField(
            model_name="member",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
