# Generated by Django 5.1.4 on 2025-12-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_member_accepted_jesus_member_began_attending_since_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="accepted_jesus",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="willing_to_be_baptized",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
