# Generated by Django 5.1.4 on 2026-01-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_alter_member_accepted_jesus_and_more"),
        ("ministries", "0004_alter_ministrymember_options_remove_assignment_user_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["status"], name="members_status_e4ea77_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["gender"], name="members_gender_d6c785_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["is_active"], name="members_is_acti_246c8e_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["status", "is_active"], name="members_status_6e6f1e_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["ministry", "status"], name="members_ministr_927f80_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["date_of_birth"], name="members_date_of_e0c244_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["wedding_anniversary"], name="members_wedding_60a1bc_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["last_name", "first_name"], name="members_last_na_ac5ab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["email"], name="members_email_d65d03_idx"),
        ),
    ]
