# Generated by Django 5.1.3 on 2026-03-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministries", "0004_alter_ministrymember_options_remove_assignment_user_and_more"),
        ("members", "0009_member_members_status_e4ea77_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="ministry_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members_secondary",
                to="ministries.ministry",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="ministry_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members_tertiary",
                to="ministries.ministry",
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["ministry_2", "status"], name="members_ministr_2_status_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["ministry_3", "status"], name="members_ministr_3_status_idx"),
        ),
    ]
