# Generated by Django 6.0.1 on 2026-03-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_member_ministry_2_member_ministry_3_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="member",
            new_name="members_ministr_dc85c8_idx",
            old_name="members_ministr_2_status_idx",
        ),
        migrations.RenameIndex(
            model_name="member",
            new_name="members_ministr_d10837_idx",
            old_name="members_ministr_3_status_idx",
        ),
    ]
