# Generated by Django 5.1.4 on 2025-12-02 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_member_attendance_rate_member_consecutive_absences_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Details of the prayer request')),
                ('category', models.CharField(choices=[('health', 'Health & Healing'), ('family', 'Family'), ('financial', 'Financial'), ('spiritual', 'Spiritual Growth'), ('relationships', 'Relationships'), ('work', 'Work/Career'), ('grief', 'Grief & Loss'), ('thanksgiving', 'Thanksgiving'), ('guidance', 'Guidance & Wisdom'), ('other', 'Other')], default='other', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide requester identity from public view')),
                ('is_private', models.BooleanField(default=False, help_text='Only visible to assigned pastors/elders')),
                ('is_public', models.BooleanField(default=False, help_text='Can be shared with congregation for prayer')),
                ('requester_name', models.CharField(blank=True, help_text='Name for non-member submissions', max_length=100)),
                ('requester_email', models.EmailField(blank=True, help_text='Email for non-member submissions', max_length=254)),
                ('requester_phone', models.CharField(blank=True, help_text='Phone for non-member submissions', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('prayed', 'Prayed For'), ('follow_up', 'Needs Follow-up'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Pastor or elder assigned to this request', limit_choices_to={'role__in': ['pastor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prayer_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, help_text='Member who submitted the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to='members.member')),
            ],
            options={
                'db_table': 'prayer_requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequestFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('prayed', 'Prayed For'), ('called', 'Phone Call Made'), ('visited', 'Home Visit'), ('counseling', 'Counseling Session'), ('email', 'Email Sent'), ('text', 'Text Message Sent'), ('meeting', 'Meeting Held'), ('note', 'Note Added'), ('other', 'Other')], default='note', max_length=20)),
                ('notes', models.TextField(help_text='Details of the follow-up action')),
                ('is_private', models.BooleanField(default=True, help_text='Private notes only visible to pastors/elders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='prayer_requests.prayerrequest')),
            ],
            options={
                'db_table': 'prayer_request_follow_ups',
                'ordering': ['-created_at'],
            },
        ),
    ]
