# Generated by Django 5.1.4 on 2025-12-04 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_member_attendance_rate_member_consecutive_absences_and_more"),
        ("prayer_requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="prayerrequest",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Pastor or elder assigned to this request",
                limit_choices_to={"role__in": ["pastor", "elder", "admin"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_prayer_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="prayerrequest",
            index=models.Index(fields=["status"], name="prayer_requ_status_0bfee3_idx"),
        ),
        migrations.AddIndex(
            model_name="prayerrequest",
            index=models.Index(fields=["priority"], name="prayer_requ_priorit_dcfae3_idx"),
        ),
        migrations.AddIndex(
            model_name="prayerrequest",
            index=models.Index(fields=["assigned_to"], name="prayer_requ_assigne_2407f3_idx"),
        ),
        migrations.AddIndex(
            model_name="prayerrequest",
            index=models.Index(fields=["-submitted_at"], name="prayer_requ_submitt_1b0a68_idx"),
        ),
    ]
