# Generated by Django 5.1.4 on 2025-12-05 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        default="SBCC Management System",
                        help_text="Application/Church name displayed throughout the system",
                        max_length=255,
                    ),
                ),
                (
                    "church_name",
                    models.CharField(
                        default="Santa Cruz Bible Christian Church",
                        help_text="Full church name",
                        max_length=255,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, default="", help_text="Church tagline or slogan", max_length=500
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Church logo (recommended: 200x200px PNG)",
                        null=True,
                        upload_to="settings/logos/",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        help_text="Church banner for headers (recommended: 1200x300px)",
                        null=True,
                        upload_to="settings/banners/",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon for browser tab (recommended: 32x32px ICO/PNG)",
                        null=True,
                        upload_to="settings/favicons/",
                    ),
                ),
                (
                    "login_background",
                    models.ImageField(
                        blank=True,
                        help_text="Background image for login page",
                        null=True,
                        upload_to="settings/backgrounds/",
                    ),
                ),
                (
                    "mission",
                    models.TextField(blank=True, default="", help_text="Church mission statement"),
                ),
                (
                    "vision",
                    models.TextField(blank=True, default="", help_text="Church vision statement"),
                ),
                (
                    "history",
                    models.TextField(blank=True, default="", help_text="Brief church history"),
                ),
                (
                    "statement_of_faith",
                    models.TextField(
                        blank=True, default="", help_text="Church statement of faith / beliefs"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", help_text="Church physical address"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", help_text="Primary contact number", max_length=50
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", help_text="Primary contact email", max_length=254
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, default="")),
                ("youtube_url", models.URLField(blank=True, default="")),
                ("instagram_url", models.URLField(blank=True, default="")),
                (
                    "service_schedule",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Church service schedule (e.g., Sunday 9:00 AM)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
