# Generated by Django 5.1.4 on 2026-01-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full name of the team member", max_length=255),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("pastor", "Pastor"),
                            ("elder", "Elder"),
                            ("deacon", "Deacon"),
                            ("staff", "Staff"),
                        ],
                        default="staff",
                        help_text="Role category",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title (e.g., 'Senior Pastor', 'Youth Director')",
                        max_length=255,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, default="", help_text="Short biography or description"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Profile photo (recommended: 300x300px)",
                        null=True,
                        upload_to="team/",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower numbers appear first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether to display this member on the public site"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="favicon",
        ),
    ]
